(in-package :v)

(defun readx (a &optional (b t) c d)
  (cl:read-preserving-whitespace a b c d))
(defun peekc (s &optional  eof-p)
  (cl:peek-char nil s eof-p))
(defun readc (s &optional (eof-p t))
  (cl:read-char     s eof-p))
(defun  eatc (s)
  (if2 (read-char s nil)))

(defconstant VT  #\Vt)
(defconstant TB  #\Tab)
(defconstant FF  #\Page)
(defconstant SP  #\Space)
(defconstant CR  #\Return)
(defconstant NL  #\Newline)
(defconstant WC  (list VT TB FF SP CR))
(defconstant WS  (cons NL WC))
(defconstant EOL (cons NL nil))

(defun sym-p (c) (mv-bind (a b) (get-macro-char c) (if a b t)))
(defun eol-p (c) (member c EOL))
(defun  wc-p (c) (member c WC))
(defun  ws-p (c) (member c WS))
