(in-package :v)
(defmacro a (&rest r) `(apply   ,@r))
(defmacro c (&rest r) `(funcall ,@r))
(defmacro n (&rest r) `(progn   ,@r))
(defmacro if3 (a b c) `(cl:if ,a ,b ,c))
(defmacro if2 (a b)   `(cl:if ,a ,b))
(defmacro mv-prog1 (&rest r) `(multiple-value-prog1 ,@r))
(defmacro mv-setq (&rest r) `(multiple-value-setq ,@r))
(defmacro mv-list (&rest r) `(multiple-value-list ,@r))
(defmacro mv-bind (&rest r) `(multiple-value-bind ,@r))
(defmacro mv-call (&rest r) `(multiple-value-call ,@r))
(defmacro get-mchar (c)
  `(let ((c ,c)) (if c (get-macro-character c))))
(defmacro set-mchar (c x &optional y)
  `(set-macro-character
    c (lambda    (&optional _1 _2 _3 _4 _5 _6 _7 _8 _9)
	(declare (ignorable _1 _2 _3 _4 _5 _6 _7 _8 _9))
	,x)
    y))
